
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Welcome to my portfolio',
  description: 'Generated by create next app',
}
export const titleIcon = (
  <Image
    src="../assets/image/hero-image.png"
    alt="Portfolio logo"
    width={32}
    height={32}
    priority
  />
)

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
     
    </html>
  )
}
